# Author: Marek K.

=begin
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Dieses Programm ist Freie Software: Sie können es unter den Bedingungen
  der GNU General Public License, wie von der Free Software Foundation,
  Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
  veröffentlichten Version, weiter verteilen und/oder modifizieren.

  Dieses Programm wird in der Hoffnung bereitgestellt, dass es nützlich sein wird, jedoch
  OHNE JEDE GEWÄHR,; sogar ohne die implizite
  Gewähr der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
  Siehe die GNU General Public License für weitere Einzelheiten.

  Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
  Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.

=end

require "rake"

$gcc = "g++"
$output = "a.exe"

desc "Create application"
task :default do
    Rake::Task[$output].invoke
end

desc "Create and run application"
task :run do
    Rake::Task[:default].execute
    puts "Execute #{$output} ..."
    system "./#{$output}"
end

desc "Create objects files"
rule ".o" => ".cpp" do |t|
    touch t.name
    system "#{$gcc} -c #{t.source} -o #{t.name}"
end

desc "Create execute file"
file $output => FileList.new("*.cpp").to_a.collect { |x| x.split(".")[0] + ".o" } do |t|
    touch t.name
    system "#{$gcc} -o #{t.name} #{t.sources.join " "}"
end

desc "Delete temp files"
task :clean do |t|
    FileList.new "*.o" do |fl|
        fl.exclude do |f|
            File.delete f
        end
        fl.ext
    end
end